application: esp8266button
version: 1
runtime: python27
api_version: 1
threadsafe: yes
instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 10m

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /_ah/mail/.+
  script: handle_incoming_email.app
  login: admin

- url: .*
  script: main.app
  
inbound_services:
- mail

libraries:
- name: webapp2
  version: "2.5.2"
